source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

workspace 'App.xcworkspace'

target 'App' do
  project 'App/App.xcodeproj'
  pod 'Alamofire', '4.8.2'
  pod 'SnapKit', '~> 4.0'
  pod 'MJRefresh'
end

target 'UlfyIOS' do
  project 'UlfyIOS/UlfyIOS.xcodeproj'
  pod 'SnapKit', '~> 4.0'
  pod 'MJRefresh'
end